openapi: 3.0.3
info:
  title: FoodSaver API
  version: "0.1"
servers:
  - url: https://api.foodsaver.example.com
paths:
  /api/auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '200':
          description: Token
  /api/products:
    get:
      summary: Obtener productos
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id: { type: integer }
                    name: { type: string }
                    price: { type: number }
    post:
      summary: Crear producto
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name: { type: string }
                price: { type: number }
                image:
                  type: string
                  format: binary
      responses:
        '201':
          description: Producto creado
