name: Android CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      working-directory: ./app
      
    - name: Lint check
      run: ./gradlew lintDebug
      working-directory: ./app
      continue-on-error: true
      
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest --continue
      working-directory: ./app
      continue-on-error: true
      
    - name: Check if test results exist
      run: |
        echo "Checking test results directory..."
        ls -la ./app/build/test-results/ || echo "No test-results directory found"
        ls -la ./app/build/test-results/testDebugUnitTest/ || echo "No testDebugUnitTest directory found"
        find ./app/build -name "*.xml" -path "*/test-results/*" || echo "No XML test files found"
      
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Android Tests
        path: |
          ./app/build/test-results/testDebugUnitTest/*.xml
          ./app/build/test-results/test*/*.xml
        reporter: java-junit
        fail-on-error: false
        
    - name: Build debug APK
      run: ./gradlew assembleDebug
      working-directory: ./app
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: debug-apk
        path: ./app/build/outputs/apk/debug/*.apk
        retention-days: 7

  build-release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      working-directory: ./app
      
    - name: Build release APK
      run: ./gradlew assembleRelease
      working-directory: ./app
      
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: ./app/build/outputs/apk/release/*.apk
        retention-days: 30
