name: Backend CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      working-directory: ./foodsaver-backend
      
    - name: Run tests
      run: ./gradlew test
      working-directory: ./foodsaver-backend
      
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Backend Tests
        path: './foodsaver-backend/build/test-results/test/*.xml'
        reporter: java-junit
        
    - name: Generate code coverage report
      run: ./gradlew jacocoTestReport
      working-directory: ./foodsaver-backend
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./foodsaver-backend/build/reports/jacoco/test/jacocoTestReport.xml
        flags: backend
        name: backend-coverage
        
    - name: Build JAR
      run: ./gradlew bootJar
      working-directory: ./foodsaver-backend
      
    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: backend-jar
        path: ./foodsaver-backend/build/libs/*.jar

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./foodsaver-backend
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/foodsaver-backend:latest
          ${{ secrets.DOCKER_USERNAME }}/foodsaver-backend:${{ github.sha }}
