name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: foodsaver_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for root gradlew
      run: chmod +x ./gradlew

    - name: Start backend (Spring Boot) in background
      run: |
        # Ejecutar desde la raíz usando la tarea del módulo para evitar cd a subcarpetas
        ./gradlew :foodsaver-backend:bootRun &
        echo $! > backend.pid
      env:
        SPRING_PROFILES_ACTIVE: test
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/foodsaver_test
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres

    - name: Wait for backend to be ready
      run: |
        echo "Waiting for backend /actuator/health..."
        timeout 120s bash -c 'until curl -sSf http://localhost:8080/actuator/health >/dev/null 2>&1; do sleep 2; done'
      # si tu actuator está en otro endpoint / puerto, ajustar URL

    # Start Android emulator and run instrumentation tests
    - name: Run instrumentation tests on emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 31           # ajustar según necesidades del proyecto
        target: google_apis
        arch: x86_64
        emulator-options: -no-window -no-audio
        script: |
          # desde la raíz ejecutamos la tarea del módulo app
          ./gradlew :app:connectedAndroidTest

    - name: Stop backend
      if: always()
      run: |
        if [ -f backend.pid ]; then
          kill $(cat backend.pid) || true
        fi
